#define preprocessor 1
#define datatype 2
#define keyword 3
#define blockcomment 4
#define operator 5
#define real 6
#define number 7
#define character 8
#define string 9
#define identifier 10
#define paranthesis 11
#define semi 12
#define comment 13